sbatch run_PAT_AL_01.sh
sbatch run_PAT_AL_02.sh
sbatch run_PAT_AL_03.sh
sbatch run_PAT_AL_04.sh
sbatch run_PAT_AL_05.sh
sbatch run_PAT_AL_06.sh
sbatch run_PAT_AL_07.sh
sbatch run_PAT_AL_08.sh
sbatch run_PAT_AL_09.sh
sbatch run_PAT_AL_10.sh
sbatch run_PAT_AL_11.sh
sbatch run_PAT_AL_12.sh
sbatch run_PAT_AL_13.sh
